language:
    python
python:
  - "2.7"
install:
  - "pip install -r dev-requirements.txt --use-mirrors"
  - "pip install coveralls"
script:
    "coverage run --source=xor setup.py test"
after_success:
    coveralls
